name: Build Firmware
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:v5.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        shell: bash
        run: |
          . $IDF_PATH/export.sh
          idf.py set-target esp32s3
          idf.py build
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/*.bin
